import { z } from 'zod';

export const BaseTypeSchema = z.enum(['ERC20', 'ERC721A', 'ERC1155']);
export type BaseType = z.infer<typeof BaseTypeSchema>;

export const ChainSchema = z.enum(['mainnet', 'sepolia', 'base', 'base-sepolia']);
export type Chain = z.infer<typeof ChainSchema>;

export const CompileRequestSchema = z.object({
  base: BaseTypeSchema,
  mechanic: z.string(),
  modules: z.array(z.string()),
  params: z.record(z.string(), z.unknown()),
  chain: ChainSchema,
});
export type CompileRequest = z.infer<typeof CompileRequestSchema>;

export const CompileResultSchema = z.object({
  configHash: z.string(),
  // URU-A08: separate identity for the exact generated bytecode. `configHash`
  // is the ConfigId (base + sorted module ids + versions).
  //
  // URU-P1-B01 (round 4): `artifactHash` is now an alias for
  // `runtimeCodeHash` — the hash of the DEPLOYED bytecode
  // (`keccak256(address.code)` on-chain). The factory's `registerImpl`
  // verifies that value against its owner-pinned entry, so the compile
  // service must expose the runtime hash for pin-and-register to work.
  // `creationCodeHash` is still returned for callers that need creation
  // identity (e.g. verifying the exact deploy tx payload).
  artifactHash: z.string(),
  creationCodeHash: z.string().optional(),
  runtimeCodeHash: z.string().optional(),
  bytecode: z.string(),
  runtimeBytecode: z.string().optional(),
  abi: z.array(z.record(z.string(), z.unknown())),
  gasEstimate: z.number().optional(),
  warnings: z.array(z.string()),
});
export type CompileResult = z.infer<typeof CompileResultSchema>;
